services:
    postgres:
        image: postgres:latest
        environment:
          POSTGRES_DB: RequestsDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: YourStrong@Passw0rd
        volumes:
          - pgdata:/var/lib/postgresql/data
        ports:
          - 5432:5432
    
    callerapp:
        image: ${DOCKER_REGISTRY-}callerapp
        build:
            context: .
            dockerfile: CallerApp/Dockerfile
        depends_on:
            - postgres

    processorapi:
        image: ${DOCKER_REGISTRY-}processorapi
        build:
            context: .
            dockerfile: ProcessorApi/Dockerfile
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@admin.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - "8085:80"
        volumes:
          - pgadmin-data:/var/lib/pgadmin
        depends_on:
          - postgres

volumes:
    pgdata:
    pgadmin-data: