services:
    postgres:
        image: postgres:latest
        environment:
          POSTGRES_DB: RequestsDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: YourStrong@Passw0rd
        volumes:
          - pgdata:/var/lib/postgresql/data
        ports:
          - 5432:5432
    
    caller-app:
        image: ${DOCKER_REGISTRY-}callerapp
        build:
            context: ./CallerApp
            dockerfile: Dockerfile

    processor-api:
        image: ${DOCKER_REGISTRY-}processorapi
        build:
            context: ./ProcessorApi
            dockerfile: Dockerfile
        depends_on:
            - postgres
            - rabbitmq

    pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@admin.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
          - "8085:80"
        volumes:
          - pgadmin-data:/var/lib/pgadmin
        depends_on:
          - postgres

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
          - "5672:5672"   # AMQP protocol
          - "15672:15672" # Management UI
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
        volumes:
          - rabbitmq-data:/var/lib/rabbitmq

volumes:
    pgdata:
    pgadmin-data:
    rabbitmq-data: