# running app in docker-compose
# @ProcessorApi_HostAddress = https://localhost:9002

# running app in minikue
@ProcessorApi_HostAddress = https://localhost:9002

GET {{ProcessorApi_HostAddress}}/

###

GET {{ProcessorApi_HostAddress}}/Logs

###

GET {{ProcessorApi_HostAddress}}/process

###

GET {{ProcessorApi_HostAddress}}/process2

###

GET {{ProcessorApi_HostAddress}}/ProcessWithMessageQueue