apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-app
  labels:
    app: caller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller-app
  template:
    metadata:
      labels:
        app: caller-app
    spec:
      containers:
        - name: caller-app
          image: kubepulse/caller-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: caller-app
  labels:
    app: caller-app
spec:
  type: NodePort
  selector:
    app: caller-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
