apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller-app
  template:
    metadata:
      labels:
        app: caller-app
    spec:
      containers:
        - name: caller-app
          image: kubepulse/caller-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: caller-app
spec:
  type: NodePort
  selector:
    app: caller-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
