apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-api
  labels:
    app: processor-api
spec:
  replicas: 1 # HPA will manage this
  selector:
    matchLabels:
      app: processor-api
  template:
    metadata:
      labels:
        app: processor-api
    spec:
      containers:
        - name: processor-api
          image: kubepulse/processor-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: processor-api
spec:
  type: ClusterIP # NodePort or ClusterIP
  selector:
    app: processor-api
  ports:
    - port: 80
      targetPort: 8080
      # nodePort: 30081 # not required when running behind a load balancer
